services:
  postgres:
    image: postgres:15
    container_name: slugrush
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: homies
      POSTGRES_PASSWORD: banana
      POSTGRES_DB: crowd_data
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
